openapi: 3.0.4
info:
  title: GreenCounter API
  description: "" 
  version: 1.0.0

servers:
  - url: http://localhost:8000/api/v1
tags:
  - name: images
    description: Изображения
  - name: stats
    description: Статистика

paths:
  /images:
    get:
      tags:
        - images
      summary: Список изображений
      description: Список изображений
      operationId: listImages
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImagesArray'

    post:
      tags:
        - images
      summary: Загрузить изображение
      description: Загрузить изображение
      operationId: addImages
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                # в ответе массив чтобы в будущем по несколько фоток загружать
                $ref: '#/components/schemas/ImagesArray'
        '422':
          description: Невалидный ввод

  /stats:
    get:
      tags:
        - stats
      summary: Статистика
      description: Статистика
      operationId: statsInfo
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                properties:
                  total:
                    type: integer
                    example: 7173
                  today_increment:
                    type: integer
                    example: 7173


components:
  schemas:
    ImagesArray:
      required:
        - id
        - segment_title
        - detected_qty
        - detected_qty_increment
        - date_of_image
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            format: int64
            example: 1
          segment_title:
            type: string
            example: 'Сегмент A1B1'
          detected_qty:
            type: integer
            example: 54
          detected_qty_increment:
            type: integer
            example: 2
          date_of_image:
            type: string
            example: '17.03.2026 18:00'
          original_image:
            type: string
            example: '/media/original_images/i_zIcPzKG.jpeg'
          processed_image:
            type: string
            example: '/media/processed_images/i.jpeg_Emee5qor.png'
